 steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    id: build
    args: ['clean', 'install']
  artifacts:
    objects:
      location: 'gs://testing-art/'
      paths: ['/workspace/target/ccdemo.war', 'cloudbuild.yaml']


